// RobotBuilder Version: 4.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide numerical or boolean
 * constants.  This class should not be used for any other purpose.  All constants should be
 * declared globally (i.e. public static).  Do not put anything functional in this class.
 *
 * <p>It is advised to statically import this class (or one of its inner classes) wherever the
 * constants are needed, to reduce verbosity.
 */
public class Constants {
    public static final class DriveConstants {

        public static final int kLeftMotorFrontPort = 1;
        public static final int kRigtMotorFrontPort = 3;
        public static final int kLeftMotorBackPort = 2;
        public static final int kRightMotorBackPort = 4;

        public static final double kAutonomousLeftDriveSpeed = .65;
        public static final double kAutonomousRightDriveSpeed = .65;

        public static final double kLeftSpeedFactor = .65;
        public static final double kRightSpeedFactor = .65;

        public static final double kSprintLeftSpeedFactor = 1.45;
        public static final double kSprintRightSpeedFactor = 1.45;

        public static final double kCrawlLeftSpeedFactor = 0.65;
        public static final double kCrawlRightSpeedFactor = 0.65;

        public static final double kOutputPower = 0.8;
        public static final double kInputPower = -0.8;
      //left drives at 93.023256% the speed of the right
      //based on 2023 stats
        public static final int kLeftShooterMotorPort = 8;
        public static final int kRightShooterMotorPort = 9;
        public static final int kLeftShooterMAXMotorPort = 6;
        public static final int kRightShooterMAXMotorPort = 7;

        public static final double kShooterMAXspinup = 0.5;
    }
}
